version: "3"

services:
  vv_test:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - PG_DB_URL=postgresql://postgres:postgres@postgres/postgres
      - PG_TEST_DB_URL=postgresql://postgres:postgres@postgres/postgres
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
