version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm rebuild node-sass
            - run: npm run build
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm rebuild node-sass
            - run: npm run test:ci

workflows:
  build-and-test:
    jobs:
      - build
      - test
