version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run test:ci
            - run: npm run build

workflows:
  build-and-test:
    jobs:
      - build-and-test
