version: "3"

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/db
      - ./db/docker-data:/var/lib/postgresql/data
