version: "3"

services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: nhs-virtual-visit-test
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      # we copy our scripts onto the container
      - ./sql:/usr/src/app
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app
    # run the entrypoint.sh that will import the data AND sqlserver
    command: sh -c ' chmod +x ./entrypoint-test.sh; ./entrypoint-test.sh & /opt/mssql/bin/sqlservr;'
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@55w0rd
