name: Sync Fork

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: (github.repository == 'Kettering-General-Hospital/nhs-virtual-visit') || (github.repository == 'London-North-West-Trust/nhs-virtual-visit')
    steps:
      - name: Fork Sync
        uses: TG908/fork-sync@v1.1.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: madetech
          base: master
          head: master
          merge_method: merge
