name: Virtual Visits Push CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "CHANGELOG.md"

  azure-deploy:
    needs: tag
    if: github.repository_owner == 'madetech'
    runs-on: ubuntu-latest

    steps:
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: actions/checkout@master
        with:
          app-name: ${{ secrets.AZUREAPPSERVICE_APP_NAME }}
          slot-name: ${{ secrets.AZUREAPPSERVICE_SLOT_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1354ACBB1422489280969781D23BDAC6 }}
          package: release
