name: Virtual Visits Push CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "CHANGELOG.md"

  azure-deploy:
    needs: tag-and-release
    if: github.repository_owner == 'madetech'
    runs-on: ubuntu-latest

    steps:
      # - name: Create and Switch to Release Folder
      #   run: |
      #     rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='__mocks__/' --exclude='test/' --exclude='docs/' --exclude='docker/' --exclude='cypress*' --exclude='jest.*' --exclude='contractTest/' --exclude='terraform/' --exclude='node_modules/' . ./release
      #     cd release
      #     ls -la

      - name: "Run Azure webapp deploy action using publish profile credentials"
        run: |
          rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='__mocks__/' --exclude='test/' --exclude='docs/' --exclude='docker/' --exclude='cypress*' --exclude='jest.*' --exclude='contractTest/' --exclude='terraform/' --exclude='node_modules/' . ./release
          cd release
          ls -la
        uses: actions/checkout@master
        with:
          app-name: ${{ secrets.AZUREAPPSERVICE_APP_NAME }}
          slot-name: ${{ secrets.AZUREAPPSERVICE_SLOT_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1354ACBB1422489280969781D23BDAC6 }}
          package: .
