name: Virtual Visits Push CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/checkout@master

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "CHANGELOG.md"

      # - name: Create Release
      #   uses: actions/create-release@v1
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.github_token }}
      #   with:
      #     tag_name: ${{ steps.changelog.outputs.tag }}
      #     release_name: ${{ steps.changelog.outputs.tag }}
      #     body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Create Release Folder
        run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='__mocks__/' --exclude='test/' --exclude='docs/' --exclude='docker/' --exclude='cypress' --exclude='contractTest/' --exclude='bin/' --exclude='db/' --exclude='node_modules/' . ./release

      - name: Switch to Release Folder
        run: |
          cd release
          ls -la

      - name: "Run Azure webapp deploy action using publish profile credentials"
        # uses: azure/webapps-deploy@v2
        uses: actions/checkout@master
        with:
          app-name: ${{ secrets.AZUREAPPSERVICE_APP_NAME }}
          slot-name: ${{ secrets.AZUREAPPSERVICE_SLOT_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1354ACBB1422489280969781D23BDAC6 }}
          package: .

  # azure-build-and-deploy:
  #   needs: tag-and-release
  #   if: github.repository_owner == 'madetech'
  #   runs-on: ubuntu-latest

  #   steps:
  #     # checkout the repo
  #     - name: "Checkout Github Action"
  #       uses: actions/checkout@master

  #     - name: Create Release Folder
  #       run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='__mocks__/' --exclude='test/' --exclude='docs/' --exclude='docker/' --exclude='cypress' --exclude='contractTest/' --exclude='bin/' --exclude='db/' --exclude='node_modules/' . ./release

  #     - name: Switch to Release Folder
  #       run: |
  #         cd release
  #         ls -la

  #     - name: "Run Azure webapp deploy action using publish profile credentials"
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ secrets.AZUREAPPSERVICE_APP_NAME }}
  #         slot-name: ${{ secrets.AZUREAPPSERVICE_SLOT_NAME }}
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1354ACBB1422489280969781D23BDAC6 }}
  #         package: .
